// Every user-facing string in the shell lives here, so externalization is a
// file swap rather than a component sweep.
export const STRINGS = {
  appTitle: "Skribeum",
  openVault: "Open vault",
  vaultTreeLabel: "Vault files",
  emptyStateHint: "No vault is open. Use “Open vault” to browse one read-only.",
  readOnlyBadge: "read-only",
  nonUtf8Banner:
    "This file is not UTF-8. It is shown read-only with unmappable bytes replaced and will never be written.",
  collisionBanner:
    "Some file names in this vault collide by letter case or Unicode form and may be merged by other filesystems:",
  vaultOpenFailed: "Opening the vault failed",
  noteReadFailed: "Reading the note failed",
  noteWriteFailed: "Saving the note failed",
  conflictBanner:
    "This note changed on disk while your edit was unsaved. The disk version was loaded and your edits were kept on top of it; review the result before saving.",
  noteRemovedBanner:
    "This note was removed from disk. Your buffer is kept as shown; saving is paused until the note reappears.",
  noteRecoveredNotice:
    "Unsaved changes from a previous session were recovered into this note. They are applied but not yet saved.",
  noteRecoveredPendingBanner:
    "Unsaved changes from a previous session were recovered. Open the note to apply them:",
  bulkDivergenceBanner:
    "More files changed at once than the review threshold. Nothing was applied automatically; review the affected files:",
  bannerReasonSizeShrank: "shrank on disk past the safety threshold",
  bannerReasonBecameEmpty: "became empty on disk",
  bannerReasonEditWithinWriteSettle:
    "changed on disk immediately after this device saved it",
  bannerReasonJournalDiverged:
    "changed on disk while the application was closed; recovered unsaved changes were not applied",
  reconciliationBannerPrefix: "Needs review:",
  reviewAction: "Review",
  dismissAction: "Dismiss",
  taskCheckboxCheckedLabel: "completed task",
  taskCheckboxUncheckedLabel: "open task",
  taskCheckboxOtherLabel: "task with a custom state",
  mathInlineLabel: "Rendered formula",
  mathBlockLabel: "Rendered equation",
  mermaidDiagramLabel: "Rendered diagram",
  mermaidLoading: "Rendering diagram",
  mermaidError: "Diagram error",
  canvasViewerLabel: "Canvas viewer",
  canvasControlsLabel: "Canvas view controls",
  canvasKeyboardHelp:
    "Use arrow keys to pan, plus and minus to zoom, and zero to reset the view.",
  canvasZoomIn: "Zoom in",
  canvasZoomOut: "Zoom out",
  canvasZoomLevel: "Zoom level",
  canvasResetView: "Reset view",
  canvasTextNodeLabel: "Canvas text card",
  canvasFileNodeLabel: "Canvas file card",
  canvasFileUnavailable: "File preview unavailable",
  canvasPreviewTruncated: "Preview truncated",
  canvasParseFailed: "The canvas file is invalid",
  editorLabel: "Note editor",
  propertiesPanelLabel: "Note properties",
  propertiesListItemLabel: "list item",
  closeAction: "Close",
  noMatches: "No matches",
  commandPaletteLabel: "Command palette",
  commandPalettePlaceholder: "Type a command name",
  commandOpenPalette: "Open command palette",
  quickSwitcherLabel: "Quick switcher",
  quickSwitcherPlaceholder: "Type a note name",
  commandOpenQuickSwitcher: "Open quick switcher",
  vaultSearchLabel: "Search vault",
  vaultSearchPlaceholder: "Search all notes",
  commandOpenVaultSearch: "Search in vault",
  vaultSearchFailed: "Searching the vault failed",
  outlineLabel: "Outline",
  outlineEmpty: "No headings",
  commandToggleOutline: "Toggle outline",
  settingsLabel: "Settings",
  commandOpenSettings: "Open settings",
  settingsTheme: "Theme",
  settingsThemeSystem: "System",
  settingsThemeLight: "Light",
  settingsThemeDark: "Dark",
  settingsFontSize: "Editor font size",
  settingsSearchLimit: "Search result limit",
  settingsReadFailed: "Reading settings failed",
  settingsWriteFailed: "Saving settings failed",
  commandSaveNote: "Save note",
  commandFindInNote: "Find in note",
  commandFindNext: "Find next match",
  commandFindPrevious: "Find previous match",
  findPlaceholder: "Find",
  replacePlaceholder: "Replace",
  findPreviousLabel: "Previous match",
  findNextLabel: "Next match",
  replaceOneLabel: "Replace match",
  replaceAllLabel: "Replace all",
  findCloseLabel: "Close find",
  findMatchSingular: "match",
  findMatchPlural: "matches",
  formatBold: "Bold",
  formatItalic: "Italic",
  formatCode: "Code",
  formatStrikethrough: "Strikethrough",
  formatWikilink: "Wikilink",
  selectionToolbarLabel: "Formatting",
  slashMenuLabel: "Insert",
  insertHeading1: "Insert heading 1",
  insertHeading2: "Insert heading 2",
  insertHeading3: "Insert heading 3",
  insertTask: "Insert task",
  insertCodeFence: "Insert code fence",
  insertCallout: "Insert callout",
  insertTable: "Insert table",
  insertWikilink: "Insert wikilink",
  slashHeading1: "Heading 1",
  slashHeading2: "Heading 2",
  slashHeading3: "Heading 3",
  slashTask: "Task",
  slashCodeFence: "Code fence",
  slashCallout: "Callout",
  slashTable: "Table",
  slashWikilink: "Wikilink",
  tableInsertRowBelow: "Table: insert row below",
  tableInsertRowAbove: "Table: insert row above",
  tableInsertColumnAfter: "Table: insert column after",
  tableInsertColumnBefore: "Table: insert column before",
} as const;
