// Every user-facing string in the shell lives here, so externalization is a
// file swap rather than a component sweep.
export const STRINGS = {
  appTitle: "Skribeum",
  openVault: "Open vault",
  commandZoomIn: "Zoom in",
  commandZoomOut: "Zoom out",
  commandZoomReset: "Reset zoom",
  nativeFileHandlingDesktopRequired:
    "Native file handling requires the desktop application.",
  desktopWindowRequired: "Window control requires the desktop application.",
  vaultTreeLabel: "Vault files",
  sidebarHeaderLabel: "Vault sidebar",
  collapseSidebar: "Collapse sidebar",
  expandSidebar: "Expand sidebar",
  collapseOutline: "Collapse outline",
  sidebarResize: "Resize sidebar",
  outlineResize: "Resize outline",
  paneResize: "Resize editor panes",
  editorPane: "Editor pane",
  remUnit: "rem",
  rowActions: "File actions",
  treeCreateNote: "New note",
  treeCreateFolder: "New folder",
  treeRename: "Rename",
  treeDelete: "Delete",
  treeMove: "Move",
  treeCopyLink: "Copy link",
  treeReveal: "Reveal in file manager",
  treeRenamePrompt: "New name",
  treeFolderPrompt: "Folder name",
  treeDeleteConfirm: "Delete this vault entry?",
  treeOperationFailed: "Changing the vault entry failed",
  toggleSidebar: "Toggle sidebar",
  toggleOutline: "Toggle outline",
  newTab: "New tab",
  closeTab: "Close tab",
  reopenClosedTab: "Reopen closed tab",
  nextTab: "Next tab",
  previousTab: "Previous tab",
  activateTab: "Activate tab",
  openTabs: "Open notes",
  allTabs: "All open notes",
  unsavedNote: "Unsaved changes",
  splitRight: "Split right",
  focusLeftPane: "Focus left pane",
  focusRightPane: "Focus right pane",
  moveTabToOtherPane: "Move tab to other pane",
  loadingContent: "Loading content",
  couldNotLoad: "Couldn't load",
  retryAction: "Retry",
  emptyStateHint: "No vault is open. Use “Open vault” to browse one read-only.",
  readOnlyBadge: "read-only",
  sourceModeBadge: "Source",
  nonUtf8Banner:
    "This file is not UTF-8. It is shown read-only with unmappable bytes replaced and will never be written.",
  collisionBanner:
    "Some file names in this vault collide by letter case or Unicode form and may be merged by other filesystems:",
  vaultOpenFailed: "Opening the vault failed",
  fileOpenFailed: "Opening the file failed",
  noteReadFailed: "Reading the note failed",
  noteNotFoundTitle: "Note not found",
  noteNotFoundPrefix: "No note exists at this vault-relative path:",
  noteNotFoundBrowser:
    "The browser demo does not create missing notes automatically.",
  noteNotFoundDesktop:
    "Create the Markdown file at this path in the vault, then refresh the vault index.",
  noteNotFoundRefresh: "Refresh and open",
  noteWriteFailed: "Saving the note failed",
  externalLinkOpenFailed: "Opening the external link failed",
  contentSwitchUnsaved:
    "The current note could not be saved. Its edits remain open in memory.",
  conflictBanner:
    "This note changed on disk while your edit was unsaved. The disk version was loaded and your edits were kept on top of it; review the result before saving.",
  noteRemovedBanner:
    "This note was removed from disk. Your buffer is kept as shown; saving is paused until the note reappears.",
  noteRecoveredNotice:
    "Unsaved changes from a previous session were recovered into this note. They are applied but not yet saved.",
  noteRecoveredPendingBanner:
    "Unsaved changes from a previous session were recovered. Open the note to apply them:",
  bulkDivergenceBanner:
    "More files changed at once than the review threshold. Nothing was applied automatically; review the affected files:",
  bannerReasonSizeShrank: "shrank on disk past the safety threshold",
  bannerReasonBecameEmpty: "became empty on disk",
  bannerReasonEditWithinWriteSettle:
    "changed on disk immediately after this device saved it",
  bannerReasonJournalDiverged:
    "changed on disk while the application was closed; recovered unsaved changes were not applied",
  reconciliationBannerPrefix: "Needs review:",
  reviewAction: "Review",
  dismissAction: "Dismiss",
  taskStatusPaletteLabel: "Task status",
  commandSetTaskStatus: "Task: set status",
  taskTrackTask: "Task",
  taskTrackTime: "Time",
  taskTrackImportance: "Importance",
  taskTrackReference: "Reference",
  taskMoreStatuses: "More statuses",
  taskDateLabel: "Due date",
  taskStatusDefaultNames: {
    " ": "Todo",
    x: "Done",
    X: "Done (alternate)",
    "-": "Cancelled",
    ">": "Forwarded",
    "<": "Scheduled",
    D: "Due",
    "?": "Question",
    "/": "Doing",
    "+": "Add",
    R: "Research",
    "!": "Important",
    i: "Idea",
    B: "Brainstorm",
    P: "Pro",
    C: "Con",
    Q: "Quote",
    N: "Note",
    b: "Bookmark",
    I: "Information",
    p: "Paraphrase",
    L: "Location",
    E: "Example",
    A: "Answer",
    r: "Reward",
    c: "Choice",
    d: "Doing",
    T: "Time",
    "@": "Character",
    t: "Talk",
    O: "Outline",
    "~": "Conflict",
    W: "World",
    f: "Clue",
    F: "Foreshadow",
    H: "Favorite",
    "&": "Symbolism",
    s: "Secret",
  },
  mathInlineLabel: "Rendered formula",
  mathBlockLabel: "Rendered equation",
  mermaidDiagramLabel: "Rendered diagram",
  mermaidLoading: "Rendering diagram",
  mermaidError: "Diagram error",
  copyCode: "Copy code",
  codeCopied: "Code copied",
  codeCopyFailed: "Copy failed",
  embedLabel: "Embedded note",
  embedLoading: "Loading embedded note",
  embedUnavailable: "Embedded note unavailable",
  embedSectionUnavailable: "Embedded section unavailable",
  embedDepthLimit: "Embed depth limit reached",
  embedCycle: "Embed cycle detected",
  linkPreviewLabel: "Link preview",
  currentNote: "Current note",
  canvasViewerLabel: "Canvas viewer",
  canvasControlsLabel: "Canvas view controls",
  canvasKeyboardHelp:
    "Use arrow keys to pan, plus and minus to zoom, and zero to reset the view.",
  canvasZoomIn: "Zoom in",
  canvasZoomOut: "Zoom out",
  canvasZoomLevel: "Zoom level",
  canvasResetView: "Reset view",
  canvasTextNodeLabel: "Canvas text card",
  canvasFileNodeLabel: "Canvas file card",
  canvasFileUnavailable: "File preview unavailable",
  canvasPreviewTruncated: "Preview truncated",
  canvasParseFailed: "The canvas file is invalid",
  editorLabel: "Note editor",
  propertiesPanelLabel: "Note properties",
  propertiesPanelTitle: "Properties",
  propertiesExpand: "Expand note properties",
  propertiesCollapse: "Collapse note properties",
  propertiesListItemLabel: "list item",
  closeAction: "Close",
  noMatches: "No matches",
  commandSurfaceLabel: "Search notes and commands",
  commandSurfacePlaceholder: "Search notes. > commands, # tags, ? in text",
  commandOpenCommandSurface: "Open search",
  commandSurfaceOpenNotes: "Open notes",
  commandSurfaceRecent: "Recent",
  commandSurfaceVault: "Vault",
  commandSurfaceCommands: "Commands and settings",
  commandSurfaceTags: "Tags",
  commandSurfaceNoteText: "Note text",
  commandSurfaceSearchTextPrefix: "Search note text for ",
  settingActionPrefix: "Setting: ",
  commandOpenPalette: "Open command palette",
  quickSwitcherLabel: "Quick switcher",
  commandOpenVaultSearch: "Search in vault",
  commandOpenFileTree: "Open file tree",
  vaultSearchFailed: "Searching the vault failed",
  outlineLabel: "Outline",
  outlineEmpty: "No headings",
  commandToggleOutline: "Toggle outline",
  copyLinkToNote: "Copy link to note",
  copyLinkToHeading: "Copy link to heading",
  copyLinkToCurrentHeading: "Copy link to current heading",
  linkCopied: "Link copied",
  linkCopyFailed: "Copying the link failed",
  settingsLabel: "Settings",
  commandOpenSettings: "Open settings",
  settingsIntro:
    "Adjust the editor, vault, search, and application preferences.",
  settingsSearchLabel: "Find a setting",
  settingsSearchPlaceholder: "Search settings",
  settingsSectionsLabel: "Settings sections",
  settingsJumpSections: "Jump to section",
  settingsSectionAppearance: "Appearance",
  settingsSectionEditor: "Editor",
  settingsSectionFiles: "Files",
  settingsSectionSearch: "Search",
  settingsSectionUpdates: "Updates",
  settingsSectionAbout: "About",
  settingsTheme: "Match system appearance",
  settingsThemeDescription:
    "Follow the system appearance using the last chosen light and dark palettes.",
  settingsPalette: "Colour palette",
  settingsLightPalette: "Light palette",
  settingsDarkPalette: "Dark palette",
  settingsPaletteDescription:
    "Choose one palette to apply its colours and light or dark appearance.",
  settingsPaletteManuscript: "Manuscript",
  settingsPaletteManuscriptDescription:
    "Paper and ink in light mode, Night Ink ground with a Jade accent in dark mode.",
  settingsPaletteStudio: "Studio",
  settingsPaletteStudioDescription:
    "Cool neutral surfaces with a clear blue accent.",
  settingsPaletteGazette: "Gazette",
  settingsPaletteGazetteDescription:
    "The highest-contrast pair, with a violet accent.",
  settingsPaletteNightroom: "Nightroom",
  settingsPaletteGraphite: "Graphite",
  settingsPaletteSignal: "Signal",
  settingsPalettePreviewBeforeLink: "Notes read well in every ",
  settingsPalettePreviewLink: "light",
  settingsPalettePreviewAfterLink: ".",
  settingsPalettePreviewCode: "skr",
  settingsPalettePreviewUncheckedTask: "Draft the outline",
  settingsPalettePreviewCheckedTask: "Ship the fix",
  settingsProseFont: "Prose font",
  settingsProseFontDescription:
    "Choose a safe system font stack for note text.",
  settingsProseFontSerif: "Book serif",
  settingsProseFontSans: "System sans",
  settingsCodeFont: "Code font",
  settingsCodeFontDescription:
    "Choose a safe system font stack for code blocks and inline code.",
  settingsCodeFontModern: "Modern monospace",
  settingsCodeFontClassic: "Classic monospace",
  settingsFontSize: "Editor font size",
  settingsFontSizeDescription:
    "Set the size of text while you write and read notes.",
  settingsLineHeight: "Line height",
  settingsLineHeightDescription:
    "Set the space between lines as a percentage of the text size.",
  settingsLineWidth: "Text column width",
  settingsLineWidthDescription:
    "Limit each line to a comfortable number of characters for reading.",
  settingsLineNumbers: "Show line numbers",
  settingsLineNumbersDescription:
    "Show a number beside each line in the editor.",
  settingsAnimations: "Use animations",
  settingsAnimationsDescription:
    "Allow interface movement when your device does not request reduced motion.",
  settingsAutosave: "Autosave delay",
  settingsAutosaveDescription:
    "Wait this many milliseconds after typing before saving your note.",
  settingsSpellCheck: "Spell check",
  settingsSpellCheckDescription:
    "Use your platform spelling tools in the editor when they are available.",
  settingsIndentStyle: "Indentation style",
  settingsIndentStyleDescription:
    "Choose whether the Tab key inserts spaces or tab characters.",
  settingsIndentSpaces: "Spaces",
  settingsIndentTabs: "Tabs",
  settingsIndentWidth: "Indentation width",
  settingsIndentWidthDescription:
    "Set how many spaces make one indentation level.",
  settingsWrapLongLines: "Wrap long lines",
  settingsWrapLongLinesDescription:
    "Keep long text visible by continuing it on the next screen line.",
  settingsInvisibles: "Show invisible characters",
  settingsInvisiblesDescription:
    "Show spaces, tabs, and line endings while editing.",
  settingsRevealSyntax: "Reveal Markdown syntax at the cursor",
  settingsRevealSyntaxDescription:
    "Show Markdown markers around the part of the note you are editing.",
  settingsLinkPreviews: "Link previews",
  settingsLinkPreviewsHint: "Hover a note link, or focus it and press P.",
  settingsTaskStatuses: "Task statuses",
  settingsTaskStatusesDescription:
    "Choose the tracks, symbols, names, and payloads used by Markdown task checkboxes.",
  settingsTaskStatusesHelp:
    "Tracks group the status menu and control newline inheritance. Next status controls a Reference status tap.",
  settingsTaskEdit: "Edit task statuses",
  settingsTaskSymbol: "Symbol",
  settingsTaskName: "Name",
  settingsTaskCategory: "Category",
  settingsTaskCategoryTodo: "To do",
  settingsTaskCategoryInProgress: "In progress",
  settingsTaskCategoryOnHold: "On hold",
  settingsTaskCategoryDone: "Done",
  settingsTaskCategoryCancelled: "Cancelled",
  settingsTaskCategoryNonTask: "Not a task",
  settingsTaskTrack: "Track",
  settingsTaskPayload: "Payload",
  settingsTaskPayloadNone: "None",
  settingsTaskPayloadDate: "Due date",
  settingsTaskPayloadLevel: "Importance level",
  settingsTaskGlyph: "Glyph",
  settingsTaskColor: "Colour token",
  settingsTaskNext: "Next status",
  settingsTaskAdd: "Add status",
  settingsTaskMoveUp: "Move status up",
  settingsTaskMoveDown: "Move status down",
  settingsTaskRemove: "Remove status",
  settingsTaskSpace: "space",
  settingsTaskNewName: "New status",
  settingsTaskInvalid:
    "Use one unique symbol, a name and glyph, and a listed theme colour variable.",
  settingsDefaultNoteFolder: "Default new-note location",
  settingsDefaultNoteFolderDescription:
    "Save new notes in this folder inside the vault. Leave it empty for the vault root.",
  settingsDefaultNoteFolderDesktopRequired:
    "Choosing a default note folder requires the desktop application.",
  settingsAttachmentFolder: "Attachment location",
  settingsAttachmentFolderDescription:
    "Choose where attachment links look for files inside the vault.",
  settingsAttachmentFolderDesktopRequired:
    "Choosing an attachment folder requires the desktop application.",
  settingsAttachmentVault: "Vault root",
  settingsAttachmentNote: "Beside the note",
  settingsAttachmentFolderChoice: "Specific folder",
  settingsAttachmentFolderPath: "Specific attachment folder",
  settingsHonorObsidian: "Use Obsidian configuration",
  settingsHonorObsidianDescription:
    "Use compatible Obsidian attachment and property settings when they are present.",
  settingsObsidianDesktopRequired:
    "Reading Obsidian configuration requires the desktop application.",
  settingsSearchLimit: "Search result limit",
  settingsSearchLimitDescription:
    "Set the maximum number of matching notes shown in a search.",
  settingsSearchBodies: "Search note text",
  settingsSearchBodiesDescription:
    "Search the text inside notes as well as their titles.",
  settingsSearchCase: "Match letter case",
  settingsSearchCaseDescription:
    "Treat uppercase and lowercase letters as different when searching.",
  settingsUpdateChannel: "Update channel",
  settingsUpdateChannelDescription:
    "Choose stable releases or earlier beta releases. Beta checks stable releases when no beta is available.",
  settingsUpdateChannelDesktopRequired:
    "Choosing an update channel requires the desktop application.",
  settingsUpdateStable: "Stable",
  settingsUpdateBeta: "Beta",
  settingsCheckUpdates: "Check for updates",
  settingsCheckUpdatesDescription:
    "Look for a newer desktop application version without interrupting your work.",
  settingsCheckUpdatesDesktopRequired:
    "Update checks require the desktop application.",
  settingsVersion: "Version",
  settingsVersionDescription: "The installed Skribeum version.",
  settingsLicense: "License",
  settingsLicenseDescription:
    "Skribeum is available under the MIT or Apache 2.0 license, at your option.",
  settingsLicenseLink: "Read the license",
  settingsRepository: "Repository",
  settingsRepositoryDescription:
    "Browse the source code and report issues in the public repository.",
  settingsRepositoryLink: "Open the repository",
  settingsThreatModel: "Security policy",
  settingsThreatModelDescription:
    "Read the application's security scope and vulnerability reporting guidance.",
  settingsThreatModelLink: "Read the security policy",
  settingsPreAlphaNote:
    "Skribeum is pre-alpha software and has not received an independent security audit.",
  settingsRestoreDefaults: "Restore defaults",
  settingsFile: "Settings file",
  settingsFileDescription:
    "The desktop file that stores these preferences outside every vault.",
  settingsFileResolving: "Locating settings.json",
  settingsFileDesktopRequired:
    "Locating the settings file requires the desktop application.",
  settingsDesktopUnavailableShort:
    "Settings file access requires the desktop application.",
  settingsDecrease: "Decrease",
  settingsIncrease: "Increase",
  settingsUnitPixels: "px",
  settingsUnitPercent: "%",
  settingsUnitCharacters: "characters",
  settingsUnitMilliseconds: "ms",
  settingsUnitSpaces: "spaces",
  settingsUnitResults: "results",
  settingsSearchTitles: "Titles only",
  settingsSearchFullText: "Titles and note text",
  settingsReadFailed: "Reading settings failed",
  settingsWriteFailed: "Saving settings failed",
  commandCreateNote: "Create new note",
  untitledNoteName: "Untitled",
  noteCreateFailed: "Creating the note failed",
  demoNoteNotMarkdown: "The requested demo file is not a note.",
  demoNoteAlreadyExists: "The requested demo note already exists.",
  commandSaveNote: "Save note",
  commandClearEditHistory: "Note: clear edit history",
  clearEditHistoryConfirmation:
    "Clear this note's edit history? Past edits, including deleted text, will be removed from this device. This cannot be undone.",
  clearEditHistoryConfirmAction: "Clear history",
  clearEditHistoryCancelAction: "Cancel",
  clearEditHistorySaveFailed:
    "The note could not be saved before clearing its edit history.",
  commandToggleSourceMode: "Toggle source mode",
  navigationHistoryLabel: "Note history",
  navigationBack: "Back",
  navigationForward: "Forward",
  overflowMenuLabel: "More actions",
  commandPaletteLabel: "Command palette",
  mobileFiles: "Files",
  mobileSearch: "Search",
  commandNavigateBack: "Navigate back",
  commandNavigateForward: "Navigate forward",
  commandFollowLink: "Follow link under cursor",
  wikilinkUnresolvedReason: "No note in this vault matches this link.",
  wikilinkTargetNotNote: "This link resolves to a file that is not a note.",
  commandFindInNote: "Find in note",
  commandFindNext: "Find next match",
  commandFindPrevious: "Find previous match",
  findPlaceholder: "Find",
  replacePlaceholder: "Replace",
  findPreviousLabel: "Previous match",
  findNextLabel: "Next match",
  replaceOneLabel: "Replace match",
  replaceAllLabel: "Replace all",
  findCloseLabel: "Close find",
  findMatchSingular: "match",
  findMatchPlural: "matches",
  formatBold: "Bold",
  formatItalic: "Italic",
  formatCode: "Code",
  formatStrikethrough: "Strikethrough",
  formatWikilink: "Wikilink",
  selectionToolbarLabel: "Formatting",
  slashMenuLabel: "Insert",
  tagMenuLabel: "Tag suggestions",
  tagSearchLabel: "Search for tag",
  commandSearchTag: "Search for tag under cursor",
  insertHeading1: "Insert heading 1",
  insertHeading2: "Insert heading 2",
  insertHeading3: "Insert heading 3",
  insertTask: "Insert task",
  insertCodeFence: "Insert code fence",
  insertCallout: "Insert callout",
  insertTable: "Insert table",
  insertWikilink: "Insert wikilink",
  updateCheck: "Check for updates",
  updateChecking: "Checking for updates",
  updateCurrent: "Skribeum is up to date",
  updateAvailable: "Update available:",
  updateDownloading: "Downloading",
  updateReady: "Update installed, restart to use",
  updateFailed: "Update check failed",
  updateUnavailable: "Updates are delivered by the desktop application",
  updateInstall: "Install update",
  slashHeading1: "Heading 1",
  slashHeading2: "Heading 2",
  slashHeading3: "Heading 3",
  slashTask: "Task",
  slashCodeFence: "Code fence",
  slashCallout: "Callout",
  slashTable: "Table",
  slashWikilink: "Wikilink",
  tableInsertRowBelow: "Table: insert row below",
  tableInsertRowAbove: "Table: insert row above",
  tableInsertColumnAfter: "Table: insert column right",
  tableInsertColumnBefore: "Table: insert column left",
  tableDeleteRow: "Table: delete row",
  tableDeleteColumn: "Table: delete column",
  tableEditSource: "Table: edit source",
  tableCellLabel: "Table cell",
  tableAppendRow: "Append table row",
  tableAppendColumn: "Append table column",
} as const;
