// Every user-facing string in the shell lives here, so externalization is a
// file swap rather than a component sweep.
export const STRINGS = {
  appTitle: "Skribeum",
  openVault: "Open vault",
  vaultTreeLabel: "Vault files",
  emptyStateHint: "No vault is open. Use “Open vault” to browse one read-only.",
  readOnlyBadge: "read-only",
  nonUtf8Banner:
    "This file is not UTF-8. It is shown read-only with unmappable bytes replaced and will never be written.",
  collisionBanner:
    "Some file names in this vault collide by letter case or Unicode form and may be merged by other filesystems:",
  vaultOpenFailed: "Opening the vault failed",
  noteReadFailed: "Reading the note failed",
  noteNotFoundTitle: "Note not found",
  noteNotFoundPrefix: "No note exists at this vault-relative path:",
  noteNotFoundBrowser:
    "The browser demo uses a fixed sample vault and cannot create missing notes.",
  noteNotFoundDesktop:
    "Create the Markdown file at this path in the vault, then refresh the vault index.",
  noteNotFoundRefresh: "Refresh and open",
  noteWriteFailed: "Saving the note failed",
  contentSwitchUnsaved:
    "The current note could not be saved. Its edits remain open in memory.",
  conflictBanner:
    "This note changed on disk while your edit was unsaved. The disk version was loaded and your edits were kept on top of it; review the result before saving.",
  noteRemovedBanner:
    "This note was removed from disk. Your buffer is kept as shown; saving is paused until the note reappears.",
  noteRecoveredNotice:
    "Unsaved changes from a previous session were recovered into this note. They are applied but not yet saved.",
  noteRecoveredPendingBanner:
    "Unsaved changes from a previous session were recovered. Open the note to apply them:",
  bulkDivergenceBanner:
    "More files changed at once than the review threshold. Nothing was applied automatically; review the affected files:",
  bannerReasonSizeShrank: "shrank on disk past the safety threshold",
  bannerReasonBecameEmpty: "became empty on disk",
  bannerReasonEditWithinWriteSettle:
    "changed on disk immediately after this device saved it",
  bannerReasonJournalDiverged:
    "changed on disk while the application was closed; recovered unsaved changes were not applied",
  reconciliationBannerPrefix: "Needs review:",
  reviewAction: "Review",
  dismissAction: "Dismiss",
  taskStatusPaletteLabel: "Task status",
  taskStatusCommandPrefix: "Set task status:",
  taskStatusDefaultNames: {
    " ": "Unchecked",
    x: "Regular",
    X: "Checked",
    "-": "Dropped",
    ">": "Forward",
    "<": "Migrated",
    D: "Date",
    "?": "Question",
    "/": "Half Done",
    "+": "Add",
    R: "Research",
    "!": "Important",
    i: "Idea",
    B: "Brainstorm",
    P: "Pro",
    C: "Con",
    Q: "Quote",
    N: "Note",
    b: "Bookmark",
    I: "Information",
    p: "Paraphrase",
    L: "Location",
    E: "Example",
    A: "Answer",
    r: "Reward",
    c: "Choice",
    d: "Doing",
    T: "Time",
    "@": "Character",
    t: "Talk",
    O: "Outline",
    "~": "Conflict",
    W: "World",
    f: "Clue",
    F: "Foreshadow",
    H: "Favorite",
    "&": "Symbolism",
    s: "Secret",
  },
  mathInlineLabel: "Rendered formula",
  mathBlockLabel: "Rendered equation",
  mermaidDiagramLabel: "Rendered diagram",
  mermaidLoading: "Rendering diagram",
  mermaidError: "Diagram error",
  copyCode: "Copy code",
  codeCopied: "Code copied",
  codeCopyFailed: "Copy failed",
  embedLabel: "Embedded note",
  embedLoading: "Loading embedded note",
  embedUnavailable: "Embedded note unavailable",
  embedSectionUnavailable: "Embedded section unavailable",
  embedDepthLimit: "Embed depth limit reached",
  embedCycle: "Embed cycle detected",
  linkPreviewLabel: "Link preview",
  currentNote: "Current note",
  canvasViewerLabel: "Canvas viewer",
  canvasControlsLabel: "Canvas view controls",
  canvasKeyboardHelp:
    "Use arrow keys to pan, plus and minus to zoom, and zero to reset the view.",
  canvasZoomIn: "Zoom in",
  canvasZoomOut: "Zoom out",
  canvasZoomLevel: "Zoom level",
  canvasResetView: "Reset view",
  canvasTextNodeLabel: "Canvas text card",
  canvasFileNodeLabel: "Canvas file card",
  canvasFileUnavailable: "File preview unavailable",
  canvasPreviewTruncated: "Preview truncated",
  canvasParseFailed: "The canvas file is invalid",
  editorLabel: "Note editor",
  propertiesPanelLabel: "Note properties",
  propertiesPanelTitle: "Properties",
  propertiesExpand: "Expand note properties",
  propertiesCollapse: "Collapse note properties",
  propertiesShowRawSource: "Show raw source",
  propertiesHideRawSource: "Hide raw source",
  propertiesListItemLabel: "list item",
  closeAction: "Close",
  noMatches: "No matches",
  commandPaletteLabel: "Command palette",
  commandPalettePlaceholder: "Type a command name",
  commandOpenPalette: "Open command palette",
  quickSwitcherLabel: "Quick switcher",
  quickSwitcherPlaceholder: "Type a note name",
  commandOpenQuickSwitcher: "Open quick switcher",
  vaultSearchLabel: "Search vault",
  vaultSearchPlaceholder: "Search all notes",
  commandOpenVaultSearch: "Search in vault",
  vaultSearchFailed: "Searching the vault failed",
  outlineLabel: "Outline",
  outlineEmpty: "No headings",
  commandToggleOutline: "Toggle outline",
  settingsLabel: "Settings",
  commandOpenSettings: "Open settings",
  settingsIntro:
    "Adjust the editor, vault, search, and application preferences.",
  settingsSearchLabel: "Find a setting",
  settingsSearchPlaceholder: "Search settings",
  settingsSectionsLabel: "Settings sections",
  settingsSectionAppearance: "Appearance",
  settingsSectionEditor: "Editor",
  settingsSectionFiles: "Files and vault",
  settingsSectionSearch: "Search",
  settingsSectionUpdates: "Updates",
  settingsSectionAbout: "About",
  settingsTheme: "Theme",
  settingsThemeSystem: "System",
  settingsThemeLight: "Light",
  settingsThemeDark: "Dark",
  settingsThemeDescription:
    "Choose whether Skribeum follows your device or uses a light or dark appearance.",
  settingsPalette: "Colour palette",
  settingsLightPalette: "Light palette",
  settingsDarkPalette: "Dark palette",
  settingsPaletteDescription:
    "Choose the named palette used for this appearance.",
  settingsPaletteManuscript: "Manuscript",
  settingsPaletteManuscriptDescription:
    "Warm paper for light mode and warm charcoal for dark mode.",
  settingsPaletteStudio: "Studio",
  settingsPaletteStudioDescription:
    "Cool neutral surfaces with a clear blue accent.",
  settingsPaletteGazette: "Gazette",
  settingsPaletteGazetteDescription:
    "The highest-contrast pair, with a violet accent.",
  settingsPaletteLamplight: "Lamplight",
  settingsPaletteGraphite: "Graphite",
  settingsPaletteSignal: "Signal",
  settingsProseFont: "Prose font",
  settingsProseFontDescription:
    "Choose a safe system font stack for note text.",
  settingsProseFontSerif: "Book serif",
  settingsProseFontSans: "System sans",
  settingsCodeFont: "Code font",
  settingsCodeFontDescription:
    "Choose a safe system font stack for code blocks and inline code.",
  settingsCodeFontModern: "Modern monospace",
  settingsCodeFontClassic: "Classic monospace",
  settingsFontSize: "Editor font size",
  settingsFontSizeDescription:
    "Set the size of text while you write and read notes.",
  settingsLineHeight: "Line height",
  settingsLineHeightDescription:
    "Set the space between lines as a percentage of the text size.",
  settingsLineWidth: "Text column width",
  settingsLineWidthDescription:
    "Limit each line to a comfortable number of characters for reading.",
  settingsLineNumbers: "Show line numbers",
  settingsLineNumbersDescription:
    "Show a number beside each line in the editor.",
  settingsAnimations: "Use animations",
  settingsAnimationsDescription:
    "Allow interface movement when your device does not request reduced motion.",
  settingsAutosave: "Autosave delay",
  settingsAutosaveDescription:
    "Wait this many milliseconds after typing before saving your note.",
  settingsSpellCheck: "Spell check",
  settingsSpellCheckDescription:
    "Use your platform spelling tools in the editor when they are available.",
  settingsIndentStyle: "Indentation style",
  settingsIndentStyleDescription:
    "Choose whether the Tab key inserts spaces or tab characters.",
  settingsIndentSpaces: "Spaces",
  settingsIndentTabs: "Tabs",
  settingsIndentWidth: "Indentation width",
  settingsIndentWidthDescription:
    "Set how many spaces make one indentation level.",
  settingsWrapLongLines: "Wrap long lines",
  settingsWrapLongLinesDescription:
    "Keep long text visible by continuing it on the next screen line.",
  settingsInvisibles: "Show invisible characters",
  settingsInvisiblesDescription:
    "Show spaces, tabs, and line endings while editing.",
  settingsRevealSyntax: "Reveal Markdown syntax at the cursor",
  settingsRevealSyntaxDescription:
    "Show Markdown markers around the part of the note you are editing.",
  settingsLinkPreviews: "Link previews",
  settingsLinkPreviewsHint: "Hover a note link, or focus it and press P.",
  settingsTaskStatuses: "Task statuses",
  settingsTaskStatusesDescription:
    "Choose the symbols, names, and click order used by Markdown task checkboxes.",
  settingsTaskStatusesHelp:
    "Order controls the status picker. Next status controls what one click selects.",
  settingsTaskEdit: "Edit task statuses",
  settingsTaskSymbol: "Symbol",
  settingsTaskName: "Name",
  settingsTaskCategory: "Category",
  settingsTaskCategoryTodo: "To do",
  settingsTaskCategoryInProgress: "In progress",
  settingsTaskCategoryOnHold: "On hold",
  settingsTaskCategoryDone: "Done",
  settingsTaskCategoryCancelled: "Cancelled",
  settingsTaskCategoryNonTask: "Not a task",
  settingsTaskGlyph: "Glyph",
  settingsTaskColor: "Colour token",
  settingsTaskNext: "Next status",
  settingsTaskAdd: "Add status",
  settingsTaskMoveUp: "Move status up",
  settingsTaskMoveDown: "Move status down",
  settingsTaskRemove: "Remove status",
  settingsTaskSpace: "space",
  settingsTaskNewName: "New status",
  settingsTaskInvalid:
    "Use one unique symbol, a name and glyph, and a listed theme colour variable.",
  settingsDefaultNoteFolder: "Default new-note location",
  settingsDefaultNoteFolderDescription:
    "Save new notes in this folder inside the vault. Leave it empty for the vault root.",
  settingsAttachmentFolder: "Attachment location",
  settingsAttachmentFolderDescription:
    "Choose where attachment links look for files inside the vault.",
  settingsAttachmentVault: "Vault root",
  settingsAttachmentNote: "Beside the note",
  settingsAttachmentFolderChoice: "Specific folder",
  settingsAttachmentFolderPath: "Specific attachment folder",
  settingsHonorObsidian: "Use Obsidian configuration",
  settingsHonorObsidianDescription:
    "Use compatible Obsidian attachment and property settings when they are present.",
  settingsDesktopOnly:
    "Desktop only. This setting is unavailable in the browser demo.",
  settingsSearchLimit: "Search result limit",
  settingsSearchLimitDescription:
    "Set the maximum number of matching notes shown in a search.",
  settingsSearchBodies: "Search note text",
  settingsSearchBodiesDescription:
    "Search the text inside notes as well as their titles.",
  settingsSearchCase: "Match letter case",
  settingsSearchCaseDescription:
    "Treat uppercase and lowercase letters as different when searching.",
  settingsUpdateChannel: "Update channel",
  settingsUpdateChannelDescription:
    "Choose stable releases or earlier beta releases. Beta checks stable releases when no beta is available.",
  settingsUpdateStable: "Stable",
  settingsUpdateBeta: "Beta",
  settingsCheckUpdates: "Check for updates",
  settingsCheckUpdatesDescription:
    "Look for a newer desktop application version without interrupting your work.",
  settingsVersion: "Version",
  settingsVersionDescription: "The version of Skribeum currently running.",
  settingsLicense: "License",
  settingsLicenseDescription:
    "Skribeum is available under the MIT or Apache 2.0 license, at your option.",
  settingsLicenseLink: "Read the license",
  settingsRepository: "Repository",
  settingsRepositoryDescription:
    "Browse the source code and report issues in the public repository.",
  settingsRepositoryLink: "Open the repository",
  settingsThreatModel: "Security policy",
  settingsThreatModelDescription:
    "Read the application's security scope and vulnerability reporting guidance.",
  settingsThreatModelLink: "Read the security policy",
  settingsPreAlphaNote:
    "Skribeum is pre-alpha software and has not received an independent security audit.",
  settingsRestoreDefaults: "Restore defaults",
  settingsFile: "Settings file",
  settingsFileDescription:
    "The desktop file that stores these preferences outside every vault.",
  settingsFileResolving: "Locating settings.json",
  settingsDesktopUnavailableShort: "Unavailable in the browser demo",
  settingsDecrease: "Decrease",
  settingsIncrease: "Increase",
  settingsUnitPixels: "px",
  settingsUnitPercent: "%",
  settingsUnitCharacters: "characters",
  settingsUnitMilliseconds: "ms",
  settingsUnitSpaces: "spaces",
  settingsUnitResults: "results",
  settingsSearchTitles: "Titles only",
  settingsSearchFullText: "Titles and note text",
  settingsReadFailed: "Reading settings failed",
  settingsWriteFailed: "Saving settings failed",
  commandCreateNote: "Create new note",
  untitledNoteName: "Untitled",
  noteCreateFailed: "Creating the note failed",
  demoNoteNotMarkdown: "The requested demo file is not a note.",
  demoNoteAlreadyExists: "The requested demo note already exists.",
  commandSaveNote: "Save note",
  navigationHistoryLabel: "Note history",
  navigationBack: "Back",
  navigationForward: "Forward",
  commandNavigateBack: "Navigate back",
  commandNavigateForward: "Navigate forward",
  commandFollowLink: "Follow link under cursor",
  wikilinkUnresolvedReason: "No note in this vault matches this link.",
  wikilinkTargetNotNote: "This link resolves to a file that is not a note.",
  commandFindInNote: "Find in note",
  commandFindNext: "Find next match",
  commandFindPrevious: "Find previous match",
  findPlaceholder: "Find",
  replacePlaceholder: "Replace",
  findPreviousLabel: "Previous match",
  findNextLabel: "Next match",
  replaceOneLabel: "Replace match",
  replaceAllLabel: "Replace all",
  findCloseLabel: "Close find",
  findMatchSingular: "match",
  findMatchPlural: "matches",
  formatBold: "Bold",
  formatItalic: "Italic",
  formatCode: "Code",
  formatStrikethrough: "Strikethrough",
  formatWikilink: "Wikilink",
  selectionToolbarLabel: "Formatting",
  slashMenuLabel: "Insert",
  insertHeading1: "Insert heading 1",
  insertHeading2: "Insert heading 2",
  insertHeading3: "Insert heading 3",
  insertTask: "Insert task",
  insertCodeFence: "Insert code fence",
  insertCallout: "Insert callout",
  insertTable: "Insert table",
  insertWikilink: "Insert wikilink",
  updateCheck: "Check for updates",
  updateChecking: "Checking for updates",
  updateCurrent: "Skribeum is up to date",
  updateAvailable: "Update available:",
  updateDownloading: "Downloading",
  updateReady: "Update installed, restart to use",
  updateFailed: "Update check failed",
  updateUnavailable: "Updates are delivered by the desktop application",
  updateInstall: "Install update",
  slashHeading1: "Heading 1",
  slashHeading2: "Heading 2",
  slashHeading3: "Heading 3",
  slashTask: "Task",
  slashCodeFence: "Code fence",
  slashCallout: "Callout",
  slashTable: "Table",
  slashWikilink: "Wikilink",
  tableInsertRowBelow: "Table: insert row below",
  tableInsertRowAbove: "Table: insert row above",
  tableInsertColumnAfter: "Table: insert column after",
  tableInsertColumnBefore: "Table: insert column before",
} as const;
