// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Opens a vault at an absolute path, validates it and indexes its tree.
	 *  This is the only command that accepts an absolute path.
	 */
	vaultOpen: (path: string) => typedError<VaultHandle, AppError>(__TAURI_INVOKE("vault_open", { path })),
	/**  Lists the indexed tree of an open vault, sorted by path. */
	vaultTree: (handle: VaultHandle) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("vault_tree", { handle })),
	/**
	 *  Re-indexes the tree of an open vault from the current filesystem state
	 *  and returns it. This is the recovery path for tree staleness after
	 *  external bulk changes or watcher overflow: the tree indexed at open
	 *  never silently drifts, it is re-read here on demand. Newly discovered
	 *  collisions re-emit, and the search index rebuilds in the background.
	 */
	vaultTreeRefresh: (handle: VaultHandle) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("vault_tree_refresh", { handle })),
	/**
	 *  Reads a note. Metadata returns as JSON; the note bytes are sent over
	 *  `content` as a single raw-payload message (an `ArrayBuffer` in the
	 *  webview), so large files never cross the bridge as JSON.
	 */
	noteRead: (handle: VaultHandle, relPath: string, content: Channel<number[]>) => typedError<NoteContent, AppError>(__TAURI_INVOKE("note_read", { handle, relPath, content })),
	/**
	 *  Reads any indexed regular file without creating editor, reconciliation,
	 *  or search-index state. This is the read path for render-only vault files.
	 */
	vaultFileRead: (handle: VaultHandle, relPath: string, content: Channel<number[]>) => typedError<VaultFileContent, AppError>(__TAURI_INVOKE("vault_file_read", { handle, relPath, content })),
	/**
	 *  Writes a note through the crash-safe change-set path: `change_set` (a
	 *  list of byte-range replacements against the last-read projection)
	 *  applies only after `expected_projection_hash` is verified against the
	 *  current on-disk projection. On mismatch nothing is written and the
	 *  conflict variant returns with the current hash and a reconciliation
	 *  handle. The delta is journaled durably before the write and committed
	 *  after it.
	 */
	noteWrite: (handle: VaultHandle, relPath: string, changeSet: ByteRangeReplace[], expectedProjectionHash: string) => typedError<WriteResult, AppError>(__TAURI_INVOKE("note_write", { handle, relPath, changeSet, expectedProjectionHash })),
	/**
	 *  Subscribes to change events under an open vault. Events arrive as the
	 *  `VaultChanged` event stream; a second subscription for the same handle is
	 *  a no-op.
	 */
	watchSubscribe: (handle: VaultHandle) => typedError<null, AppError>(__TAURI_INVOKE("watch_subscribe", { handle })),
	/**
	 *  Runs a ranked full-text query over an open vault's notes. Results carry
	 *  BM25 scores (title matches outrank heading matches outrank body
	 *  matches), a Rust-assembled snippet and byte-offset match ranges into
	 *  that snippet. At most `limit` hits return, best first.
	 */
	searchQuery: (handle: VaultHandle, query: string, limit: number) => typedError<SearchHit[], AppError>(__TAURI_INVOKE("search_query", { handle, query, limit })),
	/**
	 *  Reads the settings document from `settings.json` in the OS app-config
	 *  directory. A missing file yields the defaults.
	 */
	settingsRead: () => typedError<SettingsDoc, AppError>(__TAURI_INVOKE("settings_read")),
	/**
	 *  Writes the settings document whole. Values are validated first, and
	 *  unknown keys already present in the file are preserved, so settings
	 *  written by a newer build survive a round trip through this one.
	 */
	settingsWrite: (doc: SettingsDoc) => typedError<null, AppError>(__TAURI_INVOKE("settings_write", { doc })),
	/**
	 *  Reads a recognized Obsidian configuration file from the vault's
	 *  `.obsidian` directory, the single sanctioned read path into it. Returns
	 *  null when the file is absent, oversized or not UTF-8: configuration
	 *  degrades to defaults rather than erroring.
	 */
	vaultConfigRead: (handle: VaultHandle, name: string) => typedError<string | null, AppError>(__TAURI_INVOKE("vault_config_read", { handle, name })),
};

/** Events */
export const events = {
	bulkDivergenceReview: makeEvent<BulkDivergenceReview>("bulk-divergence-review"),
	externalNoteRemove: makeEvent<ExternalNoteRemove>("external-note-remove"),
	externalNoteUpdate: makeEvent<ExternalNoteUpdate>("external-note-update"),
	noteRecovered: makeEvent<NoteRecovered>("note-recovered"),
	reconciliationBanner: makeEvent<ReconciliationBanner>("reconciliation-banner"),
	vaultChanged: makeEvent<VaultChanged>("vault-changed"),
	vaultCollisionsDetected: makeEvent<VaultCollisionsDetected>("vault-collisions-detected"),
};

/* Types */
/**  The one error shape that crosses IPC. */
export type AppError = {
	/**
	 *  Stable machine-readable code. Codes are part of the IPC contract:
	 *  existing values never change meaning, and the committed test below
	 *  pins them.
	 */
	code: string,
	/**
	 *  Human-readable failure description. Built exclusively from error enum
	 *  display text, never from file bytes, so it cannot leak note content.
	 */
	message: string,
	/**  The vault-relative path involved, when one exists. */
	path: string | null,
};

/**  Banner reasons over IPC. */
export type BannerReason = 
/**  A stable read shrank past the guard fraction. */
"size-shrank" | 
/**  A previously non-empty note read back empty. */
"became-empty" | 
/**
 *  An external edit landed within the settle window of this device's
 *  own last write.
 */
"edit-within-write-settle" | 
/**
 *  The on-disk file changed between a crash and this start; the crash
 *  journal was not replayed.
 */
"journal-diverged";

/**
 *  More files diverged in one reconciliation pass than the review
 *  threshold; nothing was applied and the whole set needs review.
 */
export type BulkDivergenceReview = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Every divergent vault-relative path. */
	paths: string[],
};

/**
 *  One byte-range replacement over IPC: bytes `start..end` of the base
 *  (the last-read projection) are replaced by `bytes`. Offsets are UTF-8
 *  byte offsets, per the boundary invariant.
 */
export type ByteRangeReplace = {
	/**  Inclusive start byte offset into the base. */
	start: number,
	/**  Exclusive end byte offset into the base. */
	end: number,
	/**  Replacement bytes. */
	bytes: number[],
};

/**  An indexed note disappeared from disk. */
export type ExternalNoteRemove = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
};

/**
 *  A stable external change to an indexed note, delivered with a change set
 *  against this device's last-read projection so an open note ingests it as
 *  a delta. External changes are never reverted.
 */
export type ExternalNoteUpdate = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
	/**  Projection hash of the new on-disk content. */
	projection_hash: string,
	/**  Delta from the last projection to the new content. */
	change_set: ByteRangeReplace[],
};

/**
 *  Metadata for a note read. The bytes themselves travel over the raw
 *  channel passed to `note_read`, not through this JSON value; see the
 *  payload note on [`note_read`].
 */
export type NoteContent = {
	/**  Encoding classification. */
	encoding: NoteEncoding,
	/**  Lowercase hex SHA-256 over the exact on-disk bytes. Opaque. */
	projection_hash: string,
	/**  Exact byte count delivered over the channel. */
	byte_length: number,
};

/**  Encoding classification over IPC. */
export type NoteEncoding = 
/**  Valid UTF-8. */
"utf8" | 
/**  Valid UTF-8 with a byte-order mark, preserved byte-for-byte. */
"utf8-bom" | 
/**  Not UTF-8; the note is read-only. */
"non-utf8";

/**
 *  A crash-journal chain replayed on start: applying `change_set` to the
 *  current on-disk bytes reproduces the buffer as it was before the crash.
 */
export type NoteRecovered = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
	/**  Delta from the on-disk bytes to the recovered buffer. */
	change_set: ByteRangeReplace[],
	/**  Projection hash of the recovered buffer. */
	projection_hash: string,
};

/**
 *  A reconciliation banner: ambiguity the editor must surface; nothing was
 *  applied automatically.
 */
export type ReconciliationBanner = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
	/**  Why the banner is shown. */
	reason: BannerReason,
	/**  The observed on-disk projection hash, when one exists. */
	disk_hash: string | null,
};

/**
 *  One ranked full-text search result over IPC. `match_ranges` are byte
 *  offsets into `snippet` (`[start, end)`, character-boundary aligned), so
 *  the UI highlights by slicing, never by injecting markup.
 */
export type SearchHit = {
	/**  Vault-relative path of the note. */
	path: string,
	/**  Note title (final path segment without its extension). */
	title: string,
	/**  Snippet of the note text around the first match. */
	snippet: string,
	/**  Byte ranges of query-term matches inside `snippet`. */
	match_ranges: ([number, number])[],
	/**  Relevance score; higher ranks better. */
	score: number | null,
};

/**
 *  The typed settings document over IPC. Unknown keys in the underlying
 *  `settings.json` never cross the boundary; they are preserved internally
 *  on every write.
 */
export type SettingsDoc = {
	/**  Schema version of the document. */
	schema_version: number,
	/**  Color theme: `system`, `light` or `dark`. */
	theme: string,
	/**  Palette used in light mode. */
	light_palette: string,
	/**  Palette used in dark mode. */
	dark_palette: string,
	/**  Editor font size in CSS pixels. */
	editor_font_size: number,
	/**  Editor reading measure in characters. */
	editor_reading_measure: number,
	/**  Maximum number of results a search query returns. */
	search_result_limit: number,
	/**  Whether note links show rendered previews. */
	link_previews: boolean,
	/**  Ordered task marker vocabulary and click-transition graph. */
	task_statuses: TaskStatusDoc[],
};

/**  Semantic task status category over IPC. */
export type TaskStatusCategory = 
/**  An open task. */
"TODO" | 
/**  Work is underway. */
"IN_PROGRESS" | 
/**  Work is intentionally paused. */
"ON_HOLD" | 
/**  Work is complete. */
"DONE" | 
/**  Work was cancelled. */
"CANCELLED" | 
/**  A checkbox-like marker that is not a task. */
"NON_TASK";

/**  One configured task marker over IPC. */
export type TaskStatusDoc = {
	/**  The single source character between brackets. */
	symbol: string,
	/**  Human-readable status name. */
	name: string,
	/**  Semantic status category. */
	category: TaskStatusCategory,
	/**  Short glyph rendered inside the checkbox. */
	glyph: string,
	/**  Existing CSS theme custom property used for the status color. */
	color_token: string,
	/**  Symbol written by the default click transition. */
	next_status: string,
};

/**
 *  One vault tree row over IPC. Paths are vault-relative `VaultPath`
 *  strings; absolute paths never cross the boundary except into
 *  `vault_open`.
 */
export type TreeEntry = {
	/**  Vault-relative path. */
	path: string,
	/**  Entry kind. */
	kind: TreeEntryKind,
	/**  Whether the final segment is dot-prefixed. */
	hidden: boolean,
};

/**  Entry kind over IPC. */
export type TreeEntryKind = 
/**  A directory. */
"directory" | 
/**  A markdown note. */
"note" | 
/**  Any other file; listed and typed, never parsed. */
"file";

/**  Kinds of watched change. */
export type VaultChangeKind = 
/**  A file or directory appeared. */
"created" | 
/**  File content changed. */
"modified" | 
/**  A file or directory disappeared. */
"removed" | 
/**  A rename with both endpoints inside the vault. */
"renamed" | 
/**  Events were lost; the vault must be rescanned. */
"overflow";

/**
 *  A filesystem change under an open vault, delivered as a Tauri event
 *  stream after `watch_subscribe`.
 */
export type VaultChanged = {
	/**  Handle of the vault the change belongs to. */
	vault: number,
	/**  Change kind. */
	change: VaultChangeKind,
	/**  Vault-relative path, absent for overflow. */
	path: string | null,
	/**  Rename target, present only for renames. */
	renamed_to: string | null,
};

/**
 *  Case or Unicode-normalization collisions found while indexing a vault.
 *  Emitted at open; collisions are surfaced, never silently merged.
 */
export type VaultCollisionsDetected = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**
	 *  Colliding path groups, each a set of vault-relative paths that one
	 *  filesystem may treat as a single file.
	 */
	groups: string[][],
};

/**
 *  Metadata for a read-only indexed-file read. Bytes travel over the raw
 *  channel passed to `vault_file_read`.
 */
export type VaultFileContent = {
	/**  Exact byte count delivered over the channel. */
	byte_length: number,
};

/**  Opaque handle to a vault opened in this session. */
export type VaultHandle = {
	/**  Session-local identifier; never persisted. */
	id: number,
};

/**
 *  The result of `note_write`. The conflict variant is the entry point of
 *  the reconciliation UX: it carries the current on-disk projection hash
 *  plus a reconciliation handle, and nothing was overwritten.
 */
export type WriteResult = 
/**  The change set was applied and durably written. */
{ result: "written"; 
/**  Projection hash of the new on-disk bytes. */
projection_hash: string } | 
/**  The on-disk projection no longer matches the expected hash. */
{ result: "conflict"; 
/**  Current on-disk projection hash; absent when the file is gone. */
current_projection_hash: string | null; 
/**  Reconciliation handle for the conflict flow. */
reconciliation: number };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

