// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Opens a vault at an absolute path, validates it and indexes its tree.
	 *  This is the only command that accepts an absolute path.
	 */
	vaultOpen: (path: string) => typedError<VaultOpenResult, AppError>(__TAURI_INVOKE("vault_open", { path })),
	/**
	 *  Releases a native vault handle. Repeating the close is harmless so a
	 *  superseded frontend open can always clean up its provisional handle.
	 */
	vaultClose: (handle: VaultHandle) => __TAURI_INVOKE<void>("vault_close", { handle }),
	/**
	 *  Reads the device-local startup-vault session. Missing or corrupt documents
	 *  safely return an empty session.
	 */
	vaultSessionRead: () => typedError<VaultSessionDoc, AppError>(__TAURI_INVOKE("vault_session_read")),
	/**
	 *  Forgets an explicitly selected stale vault candidate. Failed opens stay
	 *  recorded until the frontend deliberately calls this command.
	 */
	vaultSessionForget: (path: string) => typedError<VaultSessionDoc, AppError>(__TAURI_INVOKE("vault_session_forget", { path })),
	/**
	 *  Clears only the authoritative startup selection while retaining recent
	 *  choices. Startup policy can still select one remaining recent vault.
	 */
	vaultSessionClearLast: () => typedError<VaultSessionDoc, AppError>(__TAURI_INVOKE("vault_session_clear_last")),
	/**  Lists the indexed tree of an open vault, sorted by path. */
	vaultTree: (handle: VaultHandle) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("vault_tree", { handle })),
	/**
	 *  Re-indexes the tree of an open vault from the current filesystem state
	 *  and returns it. This is the recovery path for tree staleness after
	 *  external bulk changes or watcher overflow: the tree indexed at open
	 *  never silently drifts, it is re-read here on demand. Newly discovered
	 *  collisions re-emit, and the search index rebuilds in the background.
	 */
	vaultTreeRefresh: (handle: VaultHandle) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("vault_tree_refresh", { handle })),
	/**
	 *  Creates an empty Markdown note at a vault-relative path without
	 *  overwriting an existing file. Missing parent folders are created inside
	 *  the vault, and the in-memory tree and search index update immediately.
	 */
	noteCreate: (handle: VaultHandle, relPath: string) => typedError<null, AppError>(__TAURI_INVOKE("note_create", { handle, relPath })),
	/**  Creates a folder inside an open vault and returns the refreshed tree. */
	treeFolderCreate: (handle: VaultHandle, relPath: string) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("tree_folder_create", { handle, relPath })),
	/**  Moves or renames one vault entry without replacing an existing entry. */
	treeEntryMove: (handle: VaultHandle, fromPath: string, toPath: string) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("tree_entry_move", { handle, fromPath, toPath })),
	/**  Deletes one vault entry and returns the refreshed tree. */
	treeEntryDelete: (handle: VaultHandle, relPath: string) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("tree_entry_delete", { handle, relPath })),
	/**  Reveals one indexed entry in the operating system file manager. */
	treeEntryReveal: (handle: VaultHandle, relPath: string) => typedError<null, AppError>(__TAURI_INVOKE("tree_entry_reveal", { handle, relPath })),
	/**
	 *  Reads a note. Metadata returns as JSON; the note bytes are sent over
	 *  `content` as a single raw-payload message (an `ArrayBuffer` in the
	 *  webview), so large files never cross the bridge as JSON.
	 */
	noteRead: (handle: VaultHandle, relPath: string, content: Channel<number[]>) => typedError<NoteContent, AppError>(__TAURI_INVOKE("note_read", { handle, relPath, content })),
	/**
	 *  Reads the creation and modification timestamps of one indexed file. The
	 *  path resolves through the vault index exactly like `note_read`, so no
	 *  unindexed path is ever statted.
	 */
	noteStat: (handle: VaultHandle, relPath: string) => typedError<NoteStat, AppError>(__TAURI_INVOKE("note_stat", { handle, relPath })),
	/**
	 *  Reads any indexed regular file without creating editor, reconciliation,
	 *  or search-index state. This is the read path for render-only vault files.
	 */
	vaultFileRead: (handle: VaultHandle, relPath: string, content: Channel<number[]>) => typedError<VaultFileContent, AppError>(__TAURI_INVOKE("vault_file_read", { handle, relPath, content })),
	/**
	 *  Overwrites one indexed non-note file's full contents. The canvas board
	 *  is the only editable consumer today: a card move, add, or remove
	 *  rewrites the whole document rather than a change-set, so this command
	 *  carries no projection-hash conflict check the way `note_write` does for
	 *  prose. It never creates editor or reconciliation state and never
	 *  touches search indexing, matching `vault_file_read`'s scope on the
	 *  write side.
	 */
	vaultFileWrite: (handle: VaultHandle, relPath: string, bytes: number[]) => typedError<null, AppError>(__TAURI_INVOKE("vault_file_write", { handle, relPath, bytes })),
	/**
	 *  Writes a note through the crash-safe change-set path: `change_set` (a
	 *  list of byte-range replacements against the last-read projection)
	 *  applies only after `expected_projection_hash` is verified against the
	 *  current on-disk projection. On mismatch nothing is written and the
	 *  conflict variant returns with the current hash and a reconciliation
	 *  handle. The delta is journaled durably before the write and committed
	 *  after it.
	 */
	noteWrite: (handle: VaultHandle, relPath: string, changeSet: ByteRangeReplace[], expectedProjectionHash: string) => typedError<WriteResult, AppError>(__TAURI_INVOKE("note_write", { handle, relPath, changeSet, expectedProjectionHash })),
	/**  Reads one note's reachable persistent undo and redo stacks. */
	editHistoryRead: (handle: VaultHandle, relPath: string) => typedError<EditHistorySnapshot, AppError>(__TAURI_INVOKE("edit_history_read", { handle, relPath })),
	/**  Appends and fsyncs a batch before the note save it describes begins. */
	editHistoryAppend: (handle: VaultHandle, relPath: string, batch: string, actions: EditHistoryAction[]) => typedError<null, AppError>(__TAURI_INVOKE("edit_history_append", { handle, relPath, batch, actions })),
	/**  Appends an external-ingest fence for one note. */
	editHistoryFence: (handle: VaultHandle, relPath: string, batch: string) => typedError<null, AppError>(__TAURI_INVOKE("edit_history_fence", { handle, relPath, batch })),
	/**  Physically removes one note's persisted edit history. */
	editHistoryClear: (handle: VaultHandle, relPath: string) => typedError<null, AppError>(__TAURI_INVOKE("edit_history_clear", { handle, relPath })),
	/**
	 *  Subscribes to change events under an open vault. Events arrive as the
	 *  `VaultChanged` event stream; a second subscription for the same handle is
	 *  a no-op.
	 */
	watchSubscribe: (handle: VaultHandle) => typedError<null, AppError>(__TAURI_INVOKE("watch_subscribe", { handle })),
	/**
	 *  Runs a ranked full-text query over an open vault's notes. Results carry
	 *  BM25 scores (title matches outrank heading matches outrank body
	 *  matches), a Rust-assembled snippet and byte-offset match ranges into
	 *  that snippet. At most `limit` hits return, best first.
	 */
	searchQuery: (handle: VaultHandle, query: string, limit: number, searchNoteBodies: boolean, caseSensitive: boolean) => typedError<SearchHit[], AppError>(__TAURI_INVOKE("search_query", { handle, query, limit, searchNoteBodies, caseSensitive })),
	/**  Returns the indexed vault tag catalog with aggregate usage counts. */
	tagCatalog: (handle: VaultHandle) => typedError<TagFrequency[], AppError>(__TAURI_INVOKE("tag_catalog", { handle })),
	updateCheck: (channel: string) => typedError<UpdateCheckDoc, AppError>(__TAURI_INVOKE("update_check", { channel })),
	/**
	 *  Reads the settings document from `settings.json` in the OS app-config
	 *  directory. A missing file yields the defaults.
	 */
	settingsRead: () => typedError<SettingsDoc, AppError>(__TAURI_INVOKE("settings_read")),
	/**
	 *  Returns the resolved settings document path for display in the settings
	 *  footer and About section.
	 */
	settingsPath: () => typedError<string, AppError>(__TAURI_INVOKE("settings_path")),
	/**
	 *  Writes the settings document whole. Values are validated first, and
	 *  unknown keys already present in the file are preserved, so settings
	 *  written by a newer build survive a round trip through this one.
	 */
	settingsWrite: (doc: SettingsDoc) => typedError<null, AppError>(__TAURI_INVOKE("settings_write", { doc })),
	/**  Persists and applies one webview zoom percentage to every window. */
	zoomSet: (zoomPercent: number) => typedError<number, AppError>(__TAURI_INVOKE("zoom_set", { zoomPercent })),
	/**
	 *  Gives Linux `WebKit` an offscreen frame in which to commit its first
	 *  paint. A no-op once the window is already revealed, so a late warmup can
	 *  never drag a visible window back to the offscreen slot.
	 */
	windowWarmup: () => typedError<null, AppError>(__TAURI_INVOKE("window_warmup")),
	/**
	 *  Applies persisted zoom before revealing the first committed frontend
	 *  render. Reveal is unconditional: a corrupt settings store or a failed
	 *  zoom application falls back to defaults and the window still shows, with
	 *  the degraded state reported only after the window is visible.
	 */
	windowReady: (webviewMs: number | null) => typedError<null, AppError>(__TAURI_INVOKE("window_ready", { webviewMs })),
	/**
	 *  Shows the window menu at the pointer, for the header's drag-region
	 *  right-click (design system section 4.13: "Right-clicking it opens the
	 *  system window menu where the platform provides one"). On Windows this is
	 *  the real platform system menu (`GetSystemMenu` and `TrackPopupMenu`),
	 *  carrying Move, Size, and keyboard-driven resize alongside Minimize,
	 *  Maximize or Restore, and Close; every other platform keeps the
	 *  predefined-item approximation, built fresh per call so it always
	 *  reflects the window's current state.
	 */
	windowShowSystemMenu: () => typedError<null, AppError>(__TAURI_INVOKE("window_show_system_menu")),
	/**
	 *  Reports the Maximize caption button's current rectangle in physical
	 *  pixels from the client area's top-left corner (design system section
	 *  4.13), keeping Windows native hit-testing in sync with the webview's own
	 *  layout so Windows 11 snap layouts appear on hover and hold over the
	 *  button, not somewhere it used to be. The webview calls this whenever the
	 *  button's own layout changes and with `None` when it should stop
	 *  answering the hit test at all (window teardown). A no-op everywhere
	 *  except Windows.
	 */
	windowSetMaximizeButtonRect: (rect: {
	/**  Left edge, physical pixels from the client area's left edge. */
	x: number | null,
	/**  Top edge, physical pixels from the client area's top edge. */
	y: number | null,
	/**  Width in physical pixels. */
	width: number | null,
	/**  Height in physical pixels. */
	height: number | null,
} | null) => typedError<null, AppError>(__TAURI_INVOKE("window_set_maximize_button_rect", { rect })),
	/**  Resolves one operating-system open-with path against known vault roots. */
	fileOpenResolve: (path: string) => typedError<OpenFileTarget, AppError>(__TAURI_INVOKE("file_open_resolve", { path })),
	/**  Drains operating-system open-with paths queued by argv or open-file events. */
	openFilesTake: () => typedError<string[], AppError>(__TAURI_INVOKE("open_files_take")),
	/**
	 *  Reads a recognized Obsidian configuration file from the vault's
	 *  `.obsidian` directory, the single sanctioned read path into it. Returns
	 *  null when the file is absent, oversized or not UTF-8: configuration
	 *  degrades to defaults rather than erroring.
	 */
	vaultConfigRead: (handle: VaultHandle, name: string) => typedError<string | null, AppError>(__TAURI_INVOKE("vault_config_read", { handle, name })),
};

/** Events */
export const events = {
	bulkDivergenceReview: makeEvent<BulkDivergenceReview>("bulk-divergence-review"),
	externalNoteRemove: makeEvent<ExternalNoteRemove>("external-note-remove"),
	externalNoteUpdate: makeEvent<ExternalNoteUpdate>("external-note-update"),
	maximizeButtonHitState: makeEvent<MaximizeButtonHitState>("maximize-button-hit-state"),
	menuCommandInvoked: makeEvent<MenuCommandInvoked>("menu-command-invoked"),
	noteRecovered: makeEvent<NoteRecovered>("note-recovered"),
	openFilesAvailable: makeEvent<OpenFilesAvailable>("open-files-available"),
	reconciliationBanner: makeEvent<ReconciliationBanner>("reconciliation-banner"),
	settingsZoomChanged: makeEvent<SettingsZoomChanged>("settings-zoom-changed"),
	vaultChanged: makeEvent<VaultChanged>("vault-changed"),
	vaultCollisionsDetected: makeEvent<VaultCollisionsDetected>("vault-collisions-detected"),
};

/* Types */
/**  The one error shape that crosses IPC. */
export type AppError = {
	/**
	 *  Stable machine-readable code. Codes are part of the IPC contract:
	 *  existing values never change meaning, and the committed test below
	 *  pins them.
	 */
	code: string,
	/**
	 *  Human-readable failure description. Built exclusively from error enum
	 *  display text, never from file bytes, so it cannot leak note content.
	 */
	message: string,
	/**  The vault-relative path involved, when one exists. */
	path: string | null,
};

/**  Banner reasons over IPC. */
export type BannerReason =
/**  A stable read shrank past the guard fraction. */
"size-shrank" |
/**  A previously non-empty note read back empty. */
"became-empty" |
/**
 *  An external edit landed within the settle window of this device's
 *  own last write.
 */
"edit-within-write-settle" |
/**
 *  The on-disk file changed between a crash and this start; the crash
 *  journal was not replayed.
 */
"journal-diverged";

/**
 *  More files diverged in one reconciliation pass than the review
 *  threshold; nothing was applied and the whole set needs review.
 */
export type BulkDivergenceReview = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Every divergent vault-relative path. */
	paths: string[],
};

/**
 *  One byte-range replacement over IPC: bytes `start..end` of the base
 *  (the last-read projection) are replaced by `bytes`. Offsets are UTF-8
 *  byte offsets, per the boundary invariant.
 */
export type ByteRangeReplace = {
	/**  Inclusive start byte offset into the base. */
	start: number,
	/**  Exclusive end byte offset into the base. */
	end: number,
	/**  Replacement bytes. */
	bytes: number[],
};

/**  One logical persistent undo-stack mutation. */
export type EditHistoryAction =
/**  Adds one transaction and clears the redo branch. */
{ kind: "entry"; entry: EditHistoryEntry } |
/**  Moves applied transactions onto the redo stack. */
{ kind: "undo"; count: number } |
/**  Moves redo transactions back onto the undo stack. */
{ kind: "redo"; count: number } |
/**  Makes every older transaction unreachable. */
{ kind: "fence" };

/**  One UTF-16 text replacement in a persisted editor transaction. */
export type EditHistoryChange = {
	/**  Inclusive UTF-16 offset in the starting document. */
	from: number,
	/**  Exclusive UTF-16 offset in the starting document. */
	to: number,
	/**  Replacement text. */
	insert: string,
};

/**  One reversible editor transaction over typed IPC. */
export type EditHistoryEntry = {
	/**  Forward changes from the before state to the after state. */
	changes: EditHistoryChange[],
	/**  Inverse changes from the after state to the before state. */
	inverse: EditHistoryChange[],
	/**  Selection before the transaction. */
	selection_before: EditHistorySelection,
	/**  Selection after the transaction. */
	selection_after: EditHistorySelection,
	/**  Required state before applying the forward changes. */
	before: EditHistoryStateCheck,
	/**  Required state before applying the inverse changes. */
	after: EditHistoryStateCheck,
};

/**  One anchor and head pair in a persisted selection. */
export type EditHistoryRange = {
	/**  Selection anchor as a UTF-16 offset. */
	anchor: number,
	/**  Selection head as a UTF-16 offset. */
	head: number,
};

/**  A complete persisted selection, including its main range. */
export type EditHistorySelection = {
	/**  Every selection range. */
	ranges: EditHistoryRange[],
	/**  Index of the main range. */
	main: number,
};

/**  The reachable edit history for one note. */
export type EditHistorySnapshot = {
	/**  Applied entries, oldest first. */
	undo: EditHistoryEntry[],
	/**  Undone entries, with the next redo at the end. */
	redo: EditHistoryEntry[],
};

/**  The document identity required before replaying a history direction. */
export type EditHistoryStateCheck = {
	/**  Document length in UTF-16 code units. */
	length: number,
	/**  Lowercase SHA-256 over the UTF-8 editor projection. */
	projection_hash: string,
};

/**  An indexed note disappeared from disk. */
export type ExternalNoteRemove = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
};

/**
 *  A stable external change to an indexed note, delivered with a change set
 *  against this device's last-read projection so an open note ingests it as
 *  a delta. External changes are never reverted.
 */
export type ExternalNoteUpdate = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
	/**  Projection hash of the bytes the change set applies to. */
	base_projection_hash: string,
	/**  Projection hash of the new on-disk content. */
	projection_hash: string,
	/**  Delta from the last projection to the new content. */
	change_set: ByteRangeReplace[],
};

/**
 *  The native hover and press state of the Windows Maximize caption button
 *  (design system section 4.13). Emitted only on Windows: a genuine
 *  `WM_NCHITTEST` result of `HTMAXBUTTON` routes real pointer input away
 *  from the webview entirely, so the button's own CSS `:hover` and
 *  `:active` never fire once native hit-testing answers for that area, and
 *  this event carries the highlight and press state back instead.
 */
export type MaximizeButtonHitState = {
	/**
	 *  Whether the cursor is currently over the button's reported
	 *  rectangle.
	 */
	hovered: boolean,
	/**  Whether the primary button is currently held down over the button. */
	pressed: boolean,
};

/**
 *  The Maximize caption button's rectangle in the same coordinate space
 *  `WM_NCHITTEST` uses after `ScreenToClient`: physical pixels measured
 *  from the client area's top-left corner. The webview reports this
 *  whenever the button's layout changes, converting its own CSS-pixel
 *  `getBoundingClientRect` through `devicePixelRatio` before it crosses the
 *  IPC boundary, so this side never needs to know the window's DPI scale.
 */
export type MaximizeButtonRect = {
	/**  Left edge, physical pixels from the client area's left edge. */
	x: number | null,
	/**  Top edge, physical pixels from the client area's top edge. */
	y: number | null,
	/**  Width in physical pixels. */
	width: number | null,
	/**  Height in physical pixels. */
	height: number | null,
};

/**
 *  A native macOS menu bar item registered against a command registry id was
 *  clicked (design system section 4.13); the frontend runs the matching
 *  command through the same registry every other surface uses.
 */
export type MenuCommandInvoked = {
	/**  The command registry id carried by the clicked menu item. */
	command: string,
};

/**
 *  Metadata for a note read. The bytes themselves travel over the raw
 *  channel passed to `note_read`, not through this JSON value; see the
 *  payload note on [`note_read`].
 */
export type NoteContent = {
	/**  Encoding classification. */
	encoding: NoteEncoding,
	/**  Lowercase hex SHA-256 over the exact on-disk bytes. Opaque. */
	projection_hash: string,
	/**  Exact byte count delivered over the channel. */
	byte_length: number,
};

/**  Encoding classification over IPC. */
export type NoteEncoding =
/**  Valid UTF-8. */
"utf8" |
/**  Valid UTF-8 with a byte-order mark, preserved byte-for-byte. */
"utf8-bom" |
/**  Not UTF-8; the note is read-only. */
"non-utf8";

/**
 *  A crash-journal chain replayed on start: applying `change_set` to the
 *  current on-disk bytes reproduces the buffer as it was before the crash.
 */
export type NoteRecovered = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
	/**  Delta from the on-disk bytes to the recovered buffer. */
	change_set: ByteRangeReplace[],
	/**  Projection hash of the recovered buffer. */
	projection_hash: string,
};

/**
 *  Filesystem timestamps for one indexed note, serving the statusline's
 *  last-edited segment and the note-info popover.
 */
export type NoteStat = {
	/**
	 *  Modification time in whole milliseconds since the Unix epoch, absent
	 *  when the platform reports none.
	 */
	modified_ms: number | null,
	/**
	 *  Creation time in whole milliseconds since the Unix epoch, absent on
	 *  filesystems that record none.
	 */
	created_ms: number | null,
};

/**  Vault and note selected for one operating-system open-with path. */
export type OpenFileTarget = {
	/**  Absolute vault root to open or retain. */
	vault_path: string,
	/**  Vault-relative note path to select. */
	note_path: string,
};

/**  A file-open request is waiting in the Rust-owned queue. */
export type OpenFilesAvailable = null;

/**
 *  A reconciliation banner: ambiguity the editor must surface; nothing was
 *  applied automatically.
 */
export type ReconciliationBanner = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**  Vault-relative path. */
	path: string,
	/**  Why the banner is shown. */
	reason: BannerReason,
	/**  The observed on-disk projection hash, when one exists. */
	disk_hash: string | null,
};

/**
 *  One ranked full-text search result over IPC. `match_ranges` are byte
 *  offsets into `snippet` (`[start, end)`, character-boundary aligned), so
 *  the UI highlights by slicing, never by injecting markup.
 */
export type SearchHit = {
	/**  Vault-relative path of the note. */
	path: string,
	/**  Note title (final path segment without its extension). */
	title: string,
	/**  Snippet of the note text around the first match. */
	snippet: string,
	/**  Byte ranges of query-term matches inside `snippet`. */
	match_ranges: ([number, number])[],
	/**  Relevance score; higher ranks better. */
	score: number | null,
};

/**
 *  The typed settings document over IPC. Unknown keys in the underlying
 *  `settings.json` never cross the boundary; they are preserved internally
 *  on every write.
 */
export type SettingsDoc = {
	/**  Schema version of the document. */
	schema_version: number,
	/**  Color theme: `system`, `light` or `dark`. */
	theme: string,
	/**  Palette used in light mode. */
	light_palette: string,
	/**  Palette used in dark mode. */
	dark_palette: string,
	/**  Prose font family choice. */
	prose_font: string,
	/**  Code font family choice. */
	code_font: string,
	/**  Editor font size in CSS pixels. */
	editor_font_size: number,
	/**  Editor line height as a percentage. */
	editor_line_height: number,
	/**  Editor line width in characters. */
	editor_line_width: number,
	/**  Application webview zoom as an integer percentage. */
	zoom_percent: number,
	/**  Whether line numbers appear beside the editor. */
	show_line_numbers: boolean,
	/**  Whether interface animations are enabled. */
	animations: boolean,
	/**  Idle delay before saving edits, in milliseconds. */
	autosave_delay_ms: number,
	/**  Whether platform spell checking is enabled. */
	spell_check: boolean,
	/**  Indentation uses spaces or tabs. */
	indent_style: string,
	/**  Indentation width in columns. */
	indent_width: number,
	/**  Whether long lines wrap in the editor. */
	wrap_long_lines: boolean,
	/**  Whether whitespace characters are shown. */
	show_invisible_characters: boolean,
	/**  Whether Markdown syntax is revealed at the cursor. */
	reveal_markdown_syntax: boolean,
	/**  Default folder for new notes, relative to the vault. */
	default_note_folder: string,
	/**  Attachment placement mode. */
	attachment_folder_mode: string,
	/**  Attachment folder, relative to the vault. */
	attachment_folder_path: string,
	/**  Whether supported Obsidian configuration is honored. */
	honor_obsidian_config: boolean,
	/**  Maximum number of results a search query returns. */
	search_result_limit: number,
	/**  Whether note links show rendered previews. */
	link_previews: boolean,
	/**  Whether note bodies are included in search. */
	search_note_bodies: boolean,
	/**  Whether search matches case sensitively. */
	search_case_sensitive: boolean,
	/**  Update release channel. */
	update_channel: string,
	/**  Whether the desktop shell asks the update server once at startup. */
	check_updates_on_startup: boolean,
	/**  Ordered task marker vocabulary and click-transition graph. */
	task_statuses: TaskStatusDoc[],
};

/**  The persisted zoom changed and every application window now uses it. */
export type SettingsZoomChanged = {
	/**  Effective webview zoom as an integer percentage. */
	zoom_percent: number,
};

/**  One tag in the indexed vault with aggregate usage counts. */
export type TagFrequency = {
	/**  Tag text without its leading hash. */
	tag: string,
	/**  Number of notes containing the tag. */
	note_count: number,
	/**  Total inline and frontmatter occurrences across indexed notes. */
	occurrence_count: number,
};

/**  Semantic task status category over IPC. */
export type TaskStatusCategory =
/**  An open task. */
"TODO" |
/**  Work is underway. */
"IN_PROGRESS" |
/**  Work is intentionally paused. */
"ON_HOLD" |
/**  Work is complete. */
"DONE" |
/**  Work was cancelled. */
"CANCELLED" |
/**  A checkbox-like marker that is not a task. */
"NON_TASK";

/**  One configured task marker over IPC. */
export type TaskStatusDoc = {
	/**  The single source character between brackets. */
	symbol: string,
	/**  Custom status name, or empty when the frontend resolves a default name. */
	name: string,
	/**  Semantic status category. */
	category: TaskStatusCategory,
	/**  Short glyph rendered inside the checkbox. */
	glyph: string,
	/**  Existing CSS theme custom property used for the status color. */
	color_token: string,
	/**  Symbol written by the default click transition. */
	next_status: string,
	/**  Optional grouping metadata. Absent fields remain absent in settings. */
	track: TaskStatusTrack | null,
	/**  Optional payload metadata. Absent fields remain absent in settings. */
	payload: TaskStatusPayload | null,
};

/**  Optional plain-text payload associated with a task status over IPC. */
export type TaskStatusPayload =
/**  An Obsidian Tasks date token. */
"date" |
/**  An importance-level token. */
"level";

/**  Track that groups a task status by its purpose over IPC. */
export type TaskStatusTrack =
/**  Ordinary task state. */
"task" |
/**  A dated task state. */
"time" |
/**  A task importance marker. */
"importance" |
/**  A user-defined reference marker. */
"reference";

/**
 *  One vault tree row over IPC. Paths are vault-relative `VaultPath`
 *  strings; absolute paths never cross the boundary except into
 *  `vault_open`.
 */
export type TreeEntry = {
	/**  Vault-relative path. */
	path: string,
	/**  Entry kind. */
	kind: TreeEntryKind,
	/**  Whether the final segment is dot-prefixed. */
	hidden: boolean,
};

/**  Entry kind over IPC. */
export type TreeEntryKind =
/**  A directory. */
"directory" |
/**  An editable Markdown or plain-text note. */
"note" |
/**  Any other file; listed and typed, never parsed. */
"file";

/**  Result of checking the selected release channel. */
export type UpdateCheckDoc =
/**  The installed version matches the selected channel manifest. */
{ kind: "current" } |
/**  A signed update is available from the selected channel manifest. */
{ kind: "available";
/**  Version announced by the manifest. */
version: string;
/**  Release notes from the manifest, when supplied. */
notes: string };

/**  Kinds of watched change. */
export type VaultChangeKind =
/**  A file or directory appeared. */
"created" |
/**  File content changed. */
"modified" |
/**  A file or directory disappeared. */
"removed" |
/**  A rename with both endpoints inside the vault. */
"renamed" |
/**  Events were lost; the vault must be rescanned. */
"overflow";

/**
 *  A filesystem change under an open vault, delivered as a Tauri event
 *  stream after `watch_subscribe`.
 */
export type VaultChanged = {
	/**  Handle of the vault the change belongs to. */
	vault: number,
	/**  Change kind. */
	change: VaultChangeKind,
	/**  Vault-relative path, absent for overflow. */
	path: string | null,
	/**  Rename target, present only for renames. */
	renamed_to: string | null,
};

/**
 *  Case or Unicode-normalization collisions found while indexing a vault.
 *  Emitted at open; collisions are surfaced, never silently merged.
 */
export type VaultCollisionsDetected = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**
	 *  Colliding path groups, each a set of vault-relative paths that one
	 *  filesystem may treat as a single file.
	 */
	groups: string[][],
};

/**
 *  Metadata for a read-only indexed-file read. Bytes travel over the raw
 *  channel passed to `vault_file_read`.
 */
export type VaultFileContent = {
	/**  Exact byte count delivered over the channel. */
	byte_length: number,
};

/**  Opaque handle to a vault opened in this session. */
export type VaultHandle = {
	/**  Session-local identifier; never persisted. */
	id: number,
};

/**
 *  The canonical vault identity and the handle that owns it for this native
 *  session. Frontend callers retain `handle` for every handle-scoped command
 *  and use `root` when they need the canonical path identity.
 */
export type VaultOpenResult = {
	/**  Opaque session-local handle for subsequent vault commands. */
	handle: VaultHandle,
	/**  Canonical absolute root accepted by the native vault model. */
	root: string,
};

/**
 *  The typed startup-vault session document. It is independent of
 *  `settings.json` so selecting a vault never changes user preferences.
 */
export type VaultSessionDoc = {
	/**  Schema version of the document. */
	schema_version: number,
	/**  Canonical root selected for automatic startup recovery, if any. */
	last_vault: string | null,
	/**  Canonical vault roots ordered newest first. */
	recent_vaults: string[],
};

/**
 *  The result of `note_write`. The conflict variant is the entry point of
 *  the reconciliation UX: it carries the current on-disk projection hash
 *  plus a reconciliation handle, and nothing was overwritten.
 */
export type WriteResult =
/**  The change set was applied and durably written. */
{ result: "written";
/**  Projection hash of the new on-disk bytes. */
projection_hash: string } |
/**  The on-disk projection no longer matches the expected hash. */
{ result: "conflict";
/**  Current on-disk projection hash; absent when the file is gone. */
current_projection_hash: string | null;
/**  Reconciliation handle for the conflict flow. */
reconciliation: number };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

