// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Opens a vault at an absolute path, validates it and indexes its tree.
	 *  This is the only command that accepts an absolute path.
	 */
	vaultOpen: (path: string) => typedError<VaultHandle, AppError>(__TAURI_INVOKE("vault_open", { path })),
	/**  Lists the indexed tree of an open vault, sorted by path. */
	vaultTree: (handle: VaultHandle) => typedError<TreeEntry[], AppError>(__TAURI_INVOKE("vault_tree", { handle })),
	/**
	 *  Reads a note. Metadata returns as JSON; the note bytes are sent over
	 *  `content` as a single raw-payload message (an `ArrayBuffer` in the
	 *  webview), so large files never cross the bridge as JSON.
	 */
	noteRead: (handle: VaultHandle, relPath: string, content: Channel<number[]>) => typedError<NoteContent, AppError>(__TAURI_INVOKE("note_read", { handle, relPath, content })),
	/**
	 *  Subscribes to change events under an open vault. Events arrive as the
	 *  `VaultChanged` event stream; a second subscription for the same handle is
	 *  a no-op.
	 */
	watchSubscribe: (handle: VaultHandle) => typedError<null, AppError>(__TAURI_INVOKE("watch_subscribe", { handle })),
};

/** Events */
export const events = {
	vaultChanged: makeEvent<VaultChanged>("vault-changed"),
	vaultCollisionsDetected: makeEvent<VaultCollisionsDetected>("vault-collisions-detected"),
};

/* Types */
/**  The one error shape that crosses IPC. */
export type AppError = {
	/**
	 *  Stable machine-readable code. Codes are part of the IPC contract:
	 *  existing values never change meaning, and the committed test below
	 *  pins them.
	 */
	code: string,
	/**
	 *  Human-readable failure description. Built exclusively from error enum
	 *  display text, never from file bytes, so it cannot leak note content.
	 */
	message: string,
	/**  The vault-relative path involved, when one exists. */
	path: string | null,
};

/**
 *  Metadata for a note read. The bytes themselves travel over the raw
 *  channel passed to `note_read`, not through this JSON value; see the
 *  payload note on [`note_read`].
 */
export type NoteContent = {
	/**  Encoding classification. */
	encoding: NoteEncoding,
	/**  Lowercase hex SHA-256 over the exact on-disk bytes. Opaque. */
	projection_hash: string,
	/**  Exact byte count delivered over the channel. */
	byte_length: number,
};

/**  Encoding classification over IPC. */
export type NoteEncoding = 
/**  Valid UTF-8. */
"utf8" | 
/**  Valid UTF-8 with a byte-order mark, preserved byte-for-byte. */
"utf8-bom" | 
/**  Not UTF-8; the note is read-only. */
"non-utf8";

/**
 *  One vault tree row over IPC. Paths are vault-relative `VaultPath`
 *  strings; absolute paths never cross the boundary except into
 *  `vault_open`.
 */
export type TreeEntry = {
	/**  Vault-relative path. */
	path: string,
	/**  Entry kind. */
	kind: TreeEntryKind,
	/**  Whether the final segment is dot-prefixed. */
	hidden: boolean,
};

/**  Entry kind over IPC. */
export type TreeEntryKind = 
/**  A directory. */
"directory" | 
/**  A markdown note. */
"note" | 
/**  Any other file; listed and typed, never parsed. */
"file";

/**  Kinds of watched change. */
export type VaultChangeKind = 
/**  A file or directory appeared. */
"created" | 
/**  File content changed. */
"modified" | 
/**  A file or directory disappeared. */
"removed" | 
/**  A rename with both endpoints inside the vault. */
"renamed" | 
/**  Events were lost; the vault must be rescanned. */
"overflow";

/**
 *  A filesystem change under an open vault, delivered as a Tauri event
 *  stream after `watch_subscribe`.
 */
export type VaultChanged = {
	/**  Handle of the vault the change belongs to. */
	vault: number,
	/**  Change kind. */
	change: VaultChangeKind,
	/**  Vault-relative path, absent for overflow. */
	path: string | null,
	/**  Rename target, present only for renames. */
	renamed_to: string | null,
};

/**
 *  Case or Unicode-normalization collisions found while indexing a vault.
 *  Emitted at open; collisions are surfaced, never silently merged.
 */
export type VaultCollisionsDetected = {
	/**  Handle of the vault concerned. */
	vault: number,
	/**
	 *  Colliding path groups, each a set of vault-relative paths that one
	 *  filesystem may treat as a single file.
	 */
	groups: string[][],
};

/**  Opaque handle to a vault opened in this session. */
export type VaultHandle = {
	/**  Session-local identifier; never persisted. */
	id: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

